version: '3'

volumes:
  db_data:
  node_modules:
  nuxt_build:
  nuxt_dist:

services:
  backend:
    build: backend
    image: compeito/wouldlist-api
    container_name: wouldlist-api
    command: /start-reload.sh
    env_file: .env
    ports:
      - "80:80"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    restart: always
  frontend:
    build: frontend
    image: compeito/wouldlist
    container_name: wouldlist
    command: yarn dev
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    restart: always
  db:
    image: mysql:5.7
    container_name: wouldlist-localdb
    env_file: .env
    expose:
      - "3306"
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    restart: always
