name: Backend

on:
  push:
    paths:
      - "backend/**.py"

jobs:
  mypy:
    name: mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          docker build --tag mkizka/wouldlist-api .
          docker run mkizka/wouldlist-api mypy app
        working-directory: ./backend
