name: Backend

on:
  push:
    paths:
      - "backend/**.py"

jobs:
  build-and-test:
    name: dockerビルドとmypyによるテスト
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          docker build --tag compeito/wouldlist-api .
          docker run compeito/wouldlist-api mypy app
        working-directory: ./backend
